# Generated by Django 4.2.1 on 2024-03-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unique_user_id', models.UUIDField(unique=True)),
                ('credit_score', models.IntegerField()),
            ],
        ),
    ]
