# Generated by Django 4.2.1 on 2024-03-21 06:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_user_aadhar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_period', models.IntegerField()),
                ('disbursement_date', models.DateField()),
                ('emi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unique_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.user')),
            ],
        ),
    ]
